language: ruby
sudo: true
rvm:
  - 2.5.1

notifications:
  slack:
    secure: BYJDRwfDjbSZ2saH679y5sFY56K6J0hi3OO4Sim4v9RXYpZNB4IIbAyWx6/hpURWaSMZtr14GyhqR/Eww2lrR2WrT/2E9m0kDoARBI7g3X6FrIeoFdC2/r1SCx3PLXtIWxYnJK3jqjSMoMDpBd6OTeZr+7xkSACZS3hJss743VVixPyMqogf3zSLmieG5AiY4HHQvW33PnQhVFtYHWxiO6Nc0XYaDqL6WmY0plhVKhuPYJD4WGXnvDzSytRvTlriXdzWkHjsvCQU36jkk/j2Pkbd6j37TueMWYbFyUaXClqoki/Phm12RUp9c3FHO0cHBHiBWysqQtVggWeAKJRTxVGjislSW1TJ5HDUoIoYIusDnAXOj4ezlMZo+xvYKWVCyJM/pedAAE/LYY5u5O3a2nMR0mALQEwBACtxX8puJDipMeDUpmTFzgJ3AbOOUEIAXSL6Vtpx+mopUqdSaXfcDdHkQ5RO+3D8RRwKL1n+nKDGvRK7OwCA8eEp/j4hoiKTBXEMJ7gDWD5oeLJpdlDMH5XUly83+wJn1V+oH7HQdCpSwKvk12/Y16e7fRLzCVUGXzTK7f6aX+jxn3SoCLCkPosfu919eQCvXNvbmqM2VaY5zD4WZ+5VxuuiEMwoTxXNEYCiwbEh3XztyhP47v7Dc8G+QDUqDn0oMKMyIb07GCw=

before_install:
  - gem update --system
  - npm install
script:
  - rake lint:styles
  - rake lint:javascript
